Update openwrt-builder.yml

diff --git a/.github/workflows/openwrt-builder.yml b/.github/workflows/openwrt-builder.yml
--- a/.github/workflows/openwrt-builder.yml
+++ b/.github/workflows/openwrt-builder.yml
@@ -204,38 +204,31 @@ jobs:
         run: |
           # 1. 确定编译列表
           DEVICES="${DEVICE_INPUT}"
-
           mkdir -p $GITHUB_WORKSPACE/firmware_collection
-
           cd /workdir/openwrt
 
           
           # 2. 设置当前设备配置文件
-          CONFIG="config/$DEVICES.config"
-            
+          CONFIG="config/$DEVICES.config"  
           echo "Using Config: $CONFIG"
+          
+          # 3. 加载配置
+          cp -f $GITHUB_WORKSPACE/$CONFIG .config
+            
+          # 4. 刷新配置并下载
+          make defconfig
+          make download -j$(nproc)
+            
+          # 5. 开始编译
+          # 使用 ccache 加速，并保留 Toolchain
+          if ! make -j$(nproc) CC="ccache gcc" CXX="ccache g++"; then
+            echo "⚠️ Multi-threaded failed, retrying single-threaded..."
+            make -j1 V=s || exit 1
+          fi
 
-          echo "Current Directory: $(pwd)"
-          find $GITHUB_WORKSPACE -maxdepth 3 -name "*.config"
-            
-            # 3. 加载配置
-            cp -f $GITHUB_WORKSPACE/$CONFIG .config
-            
-            # 4. 刷新配置并下载
-            make defconfig
-            make download -j$(nproc)
-            
-            # 5. 开始编译
-            # 使用 ccache 加速，并保留 Toolchain
-            if ! make -j$(nproc) CC="ccache gcc" CXX="ccache g++"; then
-              echo "⚠️ Multi-threaded failed, retrying single-threaded..."
-              make -j1 V=s || exit 1
-            fi
-
-            echo "✅ $DEV build finished."
-            df -hT /workdir
-            echo "::endgroup::"
-          done
+          echo "✅ $DEVICES build finished."
+          df -hT /workdir
+          echo "::endgroup::"
 
           echo "📥 Collecting artifacts"
           find bin/targets/ -name "*sysupgrade.bin" -exec cp {} $GITHUB_WORKSPACE/firmware_collection/ \;
